# -*- coding: utf-8 -*-
"""Attendance Checker.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E8q4cIfOcYYpmYL2z3SNbgde_QBIo-3c
"""

Email = input("Enter your college email:");

import pandas as pd
import requests
import io

url = "https://raw.githubusercontent.com/kashyapmanu/Attendence-Checker/main/ExportData.csv"
download = requests.get(url).content

df = pd.read_csv(io.StringIO(download.decode('utf-8')))
df['Minutes'] = df['Minutes'].astype(int)

totalClasses = len(df.groupby("Start Time").count())

present = len(df.loc[(df['Email'] == Email) & (df['Minutes'] >= 20)])

print()
print("Attendence information of ACA class")
print("Total number of classes:",totalClasses)
print("Number of class",Email,"is present:",present)
print("Number of classes absent:",(totalClasses - present))